version: "3"
services:
  database:
    restart: always
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
  app:
    restart: always
    build: .
    ports:
      - 80:5000
    volumes:
      - ./app:/ShortMe/app
    command: gunicorn --workers=4 --bind 0.0.0.0:5000 wsgi:application
  redis:
    restart: always
    image: redis
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379
volumes:
  redis_data:
